---
- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
  become: true
  tags:
    - scored
    - section3.1

- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    state: present
  become: true
  tags:
    - scored
    - section3.1
