---
- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    reload: yes
  become: true
  tags:
    - scored
    - section3.1

- name: 3.1.1 Ensure IP forwarding is disabled (Scored)
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    state: present
    reload: yes
  become: true
  tags:
    - scored
    - section3.1

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
    reload: yes
  become: true
  tags:
    - scored
    - section3.1

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
    reload: yes
  become: true
  tags:
    - scored
    - section3.1

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored)
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    state: present
    reload: yes
  become: true
  tags:
    - scored
    - section3.1

