---
- name: Get instance public IP
  uri:
    url: http://169.254.169.254/latest/meta-data/public-ipv4
    return_content: yes
  register: instance_public_ip

- name: Create instance information output file
  file:
    path: /tmp/instance-information
    state: touch

- name: Output instance IP to file
  lineinfile:
    path: /tmp/instance-information
    line: "INSTANCE_PUBLIC_IP={{ instance_public_ip.content }}"

- name: Fetch connection details for machine under build
  fetch:
    src: /tmp/instance-information
    dest: ../instance-information
    flat: yes
